nft add table inet filter {
nft add chain inet filter input { type filter hook input priority 0 \; policy drop \; }
nft add chain inet filter forward { type filter hook input priority 0 \; policy drop \; }
nft add chain inet filter output { type filter hook input priority 0 \; policy drop \; }
}
