nft add table inet filter
nft add chain input '{ type filter hook input priority 0 ; policy drop ; }' 
nft add chain forward '{ type filter hook forward priority 0 ; policy drop ; }'
nft add chain output '{ type filter hook output priority 0 ; policy drop ; }'
